/*
 * @Author: zhuchuanyong
 * @Date: 2020-02-16 22:40:45
 * @LastEditors: zhuchuanyong
 * @LastEditTime: 2020-05-10 14:05:08
 * @FilePath: \lib\page\utils\net.dart
 */

import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import '../../model/postJsonDemo.dart';
import 'package:flutter_layout_demo/utils/http.dart';
import 'dart:io';
import '../../model/banner.dart';

class NetRequestPage extends StatefulWidget {
  final String title = "网络请求";
  @override
  _NetRequestPageState createState() => _NetRequestPageState();
}

class _NetRequestPageState extends State<NetRequestPage> {
  String jsonData = "";
  void doGet() {
    XHttp.get("/weather/current/南京市").then((response) {
      setState(() {
        jsonData = response.toString();
      });
    });
  }

  void doParam() {
    XHttp.get("/music/singer/search/", {"keyWord": "周杰伦"}).then((response) {
      setState(() {
        jsonData = response.toString();
      });
    });
  }

  void setJson() async {
    //map
    final post = {'title': 'hello', 'description': 'nice'};
    print(post);
    print(post['title']);
    print(post['description']);
    print(post is Map);
    print('---------------------');

    // map 转json字符串
    final postJson = json.encode(post);
    print(postJson);
    print(postJson is String);
    print('---------------------');

    //  json字符串转map
    final postJsonConverted = json.decode(postJson);
    print(postJsonConverted);
    print(postJsonConverted['title']);
    print(postJsonConverted['description']);
    print(postJsonConverted is Map);

    print('---------------------');
    final postModel = PostJson.fromJson(postJsonConverted);
    // print('postModel:${postModel}');
    print('title:${postModel.title}');
    print('description:${postModel.description}');
    print('json转字符串:${json.encode(postModel)}}');
    Dio dio = new Dio();
    Response response =
        await dio.get("https://resources.ninghao.net/demo/posts.json");
    setState(() {
      jsonData = response.data.toString();
    });
    print(response.data);
    var mydata=PostJson.fromJson(response.data['posts'][0]);
     print(PostJson.fromJson(response.data));
     print(mydata.id);
  }

  void getHttp() async {
    Dio dio = new Dio();

    try {
      Response response =
          await dio.get("https://apimusic.zhuchuanyong.com/banner");
      // await Dio().get("https://apimusic.zhuchuanyong.com/playlist/hot");
      setState(() {
        jsonData = response.data.toString();
      });
      print('response:${response}');
      print('response.headers:${response.headers}');
      print('response.request:${response.request}');
      print('response.statusCode:${response.statusCode}');
      print('response.data:${response.data}');

      print('------------1---------');

      try {
       
        // print(response.data['banners'][0]);
        // 转成json 数据
        var DataMy=Autogenerated.fromJson(response.data);
       print("DataMy:${DataMy}");
       print("DataMy.banners:${DataMy.banners}");
       print("DataMy.code:${DataMy.code}");
       print("DataMy.banners[0].imageUrl${DataMy.banners[0].imageUrl}");
       print(DataMy.banners is List);
       DataMy.banners.forEach((item) => {
         print("item:${item}"),
         print("item.imageUrl:${item.imageUrl}")
       });

        print('------------2---------');
       
        print('------------3---------');
       
        print('------------4---------');
        

      } catch (e) {
        print(e);
      }
    } catch (e) {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Container(
        padding: const EdgeInsets.all(20),
        child: ListView(
          scrollDirection: Axis.vertical, // 水平listView,
          children: <Widget>[
            ButtonBar(
              alignment:
                  MainAxisAlignment.spaceAround, //布局方向，默认MainAxisAlignment.end
              mainAxisSize: MainAxisSize.max, //主轴大小，默认MainAxisSize.max
              children: <Widget>[
                // Button集合
                RaisedButton(
                  child: Text('Get请求'),
                  color: Colors.blue,
                  onPressed: () {
                    doGet();
                  },
                ),
                RaisedButton(
                  child: Text('post请求'),
                  color: Colors.blue,
                  onPressed: () {
                    doParam();
                  },
                ),
                RaisedButton(
                  child: Text('请求banner'),
                  color: Colors.blue,
                  onPressed: () {
                    getHttp();
                  },
                ),

                RaisedButton(
                  child: Text('序列化测试'),
                  color: Colors.blue,
                  onPressed: () {
                    setJson();
                  },
                ),
              ],
            ),
            Text('网络请求结果：\n$jsonData',
                style: TextStyle(fontSize: 14), textAlign: TextAlign.left),
          ],
        ),
      ),
    );
  }
}
